name: primer build and package...
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@5
      
      - name: configurar Nodejs
        uses:  actions/setup-node@v6
        with:
          node-version: '20'

      - name: install dependencias
        run: npm install

      - name: build oki
        run: npm run build --if-present

      - name: package application oki
        run: tar -czf app.tar.gz app.js package.json package-lock.json Dockerfile

      - name: cargar artefacto
        uses: actions/upload-artifact@v5
        with:
          name: node-app
          path: app.tar.gz



        
        
